name: smart_parking_finder_flutter
description: Flutter and Firebase Smart Parking Finder prototype for SETaP Coursework 2.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0

  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
