/// An immutable snapshot of a single parking space.
///
/// Instances are generated by [ParkingService.generateParkingSpaces] and
/// persisted via [ParkingRepository]. Availability figures ([availableSpaces]
/// and [previousAvailableSpaces]) are refreshed periodically through
/// [ParkingService.refreshAvailability] to simulate live occupancy updates.
class ParkingSpace {
  /// Creates a [ParkingSpace] with all required fields.
  const ParkingSpace({
    required this.id,
    required this.name,
    required this.latitude,
    required this.longitude,
    required this.pricePerHour,
    required this.availableSpaces,
    required this.previousAvailableSpaces,
    required this.totalSpaces,
    required this.type,
    required this.hasLighting,
    required this.safetyScore,
    required this.openingHours,
    required this.restrictions,
    required this.bayWidth,
    required this.notes,
  });

  /// Unique identifier for this parking space (e.g. `"p1"`).
  ///
  /// Used as the Firestore document ID when persisting via
  /// [ParkingRepository.replaceParkingSpaces].
  final String id;

  /// Human-readable name of the car park, prefixed with the destination name.
  final String name;

  /// WGS-84 latitude in decimal degrees.
  final double latitude;

  /// WGS-84 longitude in decimal degrees.
  final double longitude;

  /// Hourly parking charge in GBP (£).
  final double pricePerHour;

  /// Number of spaces currently available.
  ///
  /// A value of `0` means the car park is full and it is excluded from
  /// filter results by [ParkingService.filterParkingSpaces].
  final int availableSpaces;

  /// [availableSpaces] value from the previous refresh cycle.
  ///
  /// Used by [ParkingService.refreshAvailability] to determine whether
  /// occupancy is trending up or down, producing a realistic oscillation
  /// rather than random noise.
  final int previousAvailableSpaces;

  /// Total number of bays in the car park.
  final int totalSpaces;

  /// Category of the car park: `"standard"`, `"wide"`, or `"disabled"`.
  final String type;

  /// Whether the car park has artificial lighting (relevant to the Evening
  /// quick-filter preset).
  final bool hasLighting;

  /// Safety rating from 1 (lowest) to 5 (highest) assigned by the data set.
  final int safetyScore;

  /// Human-readable description of opening times (e.g. `"24 hours"`).
  final String openingHours;

  /// Restrictions that apply to this car park (e.g. maximum stay, permit).
  final String restrictions;

  /// Physical bay width category: `"standard"` or `"wide"`.
  final String bayWidth;

  /// Additional free-text notes displayed on the details screen.
  final String notes;

  /// Deserialises a [ParkingSpace] from a Firestore document map.
  ///
  /// Missing or null fields fall back to sensible defaults so that partially
  /// migrated documents do not cause runtime errors.
  factory ParkingSpace.fromMap(String id, Map<String, dynamic> data) {
    return ParkingSpace(
      id: id,
      name: data['name'] as String? ?? 'Unknown parking',
      latitude: (data['latitude'] as num? ?? 0).toDouble(),
      longitude: (data['longitude'] as num? ?? 0).toDouble(),
      pricePerHour: (data['pricePerHour'] as num? ?? 0).toDouble(),
      availableSpaces: (data['availableSpaces'] as num? ?? 0).toInt(),
      previousAvailableSpaces:
          (data['previousAvailableSpaces'] as num? ?? 0).toInt(),
      totalSpaces: (data['totalSpaces'] as num? ?? 0).toInt(),
      type: data['type'] as String? ?? 'standard',
      hasLighting: data['hasLighting'] as bool? ?? false,
      safetyScore: (data['safetyScore'] as num? ?? 0).toInt(),
      openingHours: data['openingHours'] as String? ?? 'Unknown',
      restrictions: data['restrictions'] as String? ?? 'None',
      bayWidth: data['bayWidth'] as String? ?? 'standard',
      notes: data['notes'] as String? ?? '',
    );
  }

  /// Serialises this [ParkingSpace] to a Firestore-compatible map.
  ///
  /// The document ID ([id]) is intentionally excluded because Firestore stores
  /// it separately as the document key.
  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'latitude': latitude,
      'longitude': longitude,
      'pricePerHour': pricePerHour,
      'availableSpaces': availableSpaces,
      'previousAvailableSpaces': previousAvailableSpaces,
      'totalSpaces': totalSpaces,
      'type': type,
      'hasLighting': hasLighting,
      'safetyScore': safetyScore,
      'openingHours': openingHours,
      'restrictions': restrictions,
      'bayWidth': bayWidth,
      'notes': notes,
    };
  }

  /// Returns a copy of this [ParkingSpace] with the specified fields replaced.
  ///
  /// Used by [ParkingService.generateParkingSpaces] to apply per-destination
  /// coordinate offsets to the base templates, and by
  /// [ParkingService.refreshAvailability] to update occupancy figures.
  ParkingSpace copyWith({
    String? id,
    String? name,
    double? latitude,
    double? longitude,
    double? pricePerHour,
    int? availableSpaces,
    int? previousAvailableSpaces,
    int? totalSpaces,
    String? type,
    bool? hasLighting,
    int? safetyScore,
    String? openingHours,
    String? restrictions,
    String? bayWidth,
    String? notes,
  }) {
    return ParkingSpace(
      id: id ?? this.id,
      name: name ?? this.name,
      latitude: latitude ?? this.latitude,
      longitude: longitude ?? this.longitude,
      pricePerHour: pricePerHour ?? this.pricePerHour,
      availableSpaces: availableSpaces ?? this.availableSpaces,
      previousAvailableSpaces:
          previousAvailableSpaces ?? this.previousAvailableSpaces,
      totalSpaces: totalSpaces ?? this.totalSpaces,
      type: type ?? this.type,
      hasLighting: hasLighting ?? this.hasLighting,
      safetyScore: safetyScore ?? this.safetyScore,
      openingHours: openingHours ?? this.openingHours,
      restrictions: restrictions ?? this.restrictions,
      bayWidth: bayWidth ?? this.bayWidth,
      notes: notes ?? this.notes,
    );
  }
}
